databases:
  - name: budget_app
    plan: free
    databaseName: budget_db
    user: budgetapp_user

services:
  - type: web
    name: budgetapp_sandeep
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false